version: "3.9"
services:
  worker:
    # build: ./worker
    image: fathombot/worker:latest
    volumes:
      - /tmp:/tmp
    environment:
      - LIQUIDATOR_ADDRESS=0xe7B11F39E08089B1d76A79D6272AC7Ad11E8eFe9
      - LIQUIDATOR_PRIVATE_KEY=aa926a94cfe6e189c8f7915c969cb158a5d00680868061d1771e3a8a47615b8b
      - NETWORK_ID=51
      - MONGODB_URL=
      - LIQUIDATION_INTERVAL=5000
    ipc: "host"
  position-manager:
    # build: ./position-manager
    image: fathombot/position-manager:latest
    depends_on:
      - worker
    volumes:
      - /tmp:/tmp
    environment:
      - NETWORK_ID=51
      - MONGODB_URL=
    ipc: "host"
  redis:
    image: redis:6.2.5-alpine
