version: "3.9"
services:
  worker:
    build: ./worker
    volumes:
      - /tmp:/tmp
    env_file:
      - .env
    ipc: "host"
  position-manager:
    build: ./position-manager
    environment:
      - REDIS_SERVER_IP=redis-server
    depends_on:
      - worker
    volumes:
      - /tmp:/tmp
    env_file:
      - .env
    ipc: "host"
  redis:
    image: redis:6.2.5-alpine
