version: "3.9"
services:
  worker:
    build: ./worker
    volumes:
      - /tmp:/tmp
    env_file:
      - .env
    ipc: "host"
  position-manager:
    build: ./position-manager
    depends_on:
      - worker
    volumes:
      - /tmp:/tmp
    env_file:
      - .env
    ipc: "host"
