version: "3.9"
services:
  worker:
    image: fathombot/worker:latest
    depends_on:
      - redis
    volumes:
      - /tmp:/tmp
    environment:
      - LIQUIDATOR_ADDRESS=0xe7B11F39E08089B1d76A79D6272AC7Ad11E8eFe9
      - NETWORK_ID=51
      - LIQUIDATION_BATCH_SIZE=100
      - LIQUIDATION_INTERVAL=5000
    ipc: "host"
    restart: always
    entrypoint: "/bin/sh -c 'LIQUIDATOR_PRIVATE_KEY=`cat /run/secrets/liquidator_bot_pk` MONGODB_URL=`cat /run/secrets/mongodb_connection_string`  npm run start'"
    secrets:
     - liquidator_bot_pk
     - mongodb_connection_string
  position-manager:
    image: fathombot/position-manager:latest
    depends_on:
      - worker
      - redis
    volumes:
      - /tmp:/tmp
    environment:
      - LIQUIDATOR_ADDRESS=0xe7B11F39E08089B1d76A79D6272AC7Ad11E8eFe9
      - NETWORK_ID=51
    ipc: "host"
    restart: always
    entrypoint: "/bin/sh -c 'MONGODB_URL=`cat /run/secrets/mongodb_connection_string` npm run start'"
    secrets:
     - mongodb_connection_string

  redis:
    image: redis:6.2.5-alpine
    restart: always
secrets:
  liquidator_bot_pk:
    external: true
  mongodb_connection_string:
    external: true